/**
 * Seed data for the project management dashboard.
 * Derived from the 8 project summary files in /projects/.
 */

const SEED_DATA = {
  projects: [
    {
      id: 'cat-herding',
      name: 'Cat Herding',
      tagline: 'Claude Code plugin marketplace & developer tools',
      status: 'active',
      techStack: ['Claude Code Plugins', 'TypeScript/Hono', 'React 19', 'Cloudflare Workers', 'Railway'],
      path: '~/projects/personal/cat-herding/',
      branch: 'main',
      uncommitted: true,
      uncommittedDetail: '1 modified/untracked files',
      openBranches: ['feature/yolo-install-uninstall'],
      branchSummaries: {
        'feature/yolo-install-uninstall': 'Adding install/uninstall commands for YOLO plugin',
      },
      latestWork: 'Mark Phase 9 complete, add smoke test docs. Template fixes from e2e smoke test run. Add test smoke/validate commands (v1.1.0).',
      runCmd: 'claude --plugin-dir ./plugins/webinitor',
      tags: ['plugins', 'infrastructure', 'scaffolding'],
    },
    {
      id: 'my-agentic-interviews',
      name: 'My Agentic Interviews',
      tagline: 'Structured knowledge capture for technical project interviews',
      status: 'active',
      techStack: ['Markdown', 'YAML Frontmatter', 'Git'],
      path: '~/projects/personal/my-agentic-interviews/',
      branch: 'main',
      uncommitted: true,
      uncommittedDetail: '24 modified/untracked files',
      openBranches: [],
      latestWork: 'Built Whippet (macOS menu bar app) cookbook recipes covering lifecycle, UI, persistence, notifications, events. 21 recipes recently deleted — needs commit.',
      runCmd: '/interview',
      tags: ['documentation', 'knowledge-management'],
    },
    {
      id: 'mysetup',
      name: 'mysetup',
      tagline: 'Dev environment automation for macOS and Windows/WSL',
      status: 'active',
      techStack: ['Bash/Zsh', 'Python 3', 'Oh-my-zsh', 'Homebrew'],
      path: '~/projects/personal/mysetup/',
      branch: 'main',
      uncommitted: true,
      uncommittedDetail: '7 modified/untracked files',
      openBranches: ['housekeeping-updates', 'remove-deprecated'],
      branchSummaries: {
        'remove-deprecated': 'Cleaning out 4.5MB of legacy code from deprecated/ directory',
        'housekeeping-updates': 'Housekeeping and cleanup tasks',
      },
      latestWork: 'Phase 1 of /setup skill (declarative manifest). Cleaned up config repos & Claude plugins. Preparing remove-deprecated branch for legacy code cleanup.',
      runCmd: './install.sh',
      tags: ['automation', 'devtools', 'shell'],
    },
    {
      id: 'name-craft',
      name: 'Name Craft',
      tagline: 'AI-powered silly character name generator',
      status: 'stable',
      techStack: ['Flask 3.0', 'Python 3', 'Claude API', 'SQLite', 'SSE'],
      path: '~/projects/personal/name-craft/',
      branch: 'main',
      uncommitted: false,
      uncommittedDetail: '',
      openBranches: [],
      latestWork: 'Added silly words pool to name-components reference. Word builder DB scaffolding complete. Core system fully functional with mock mode.',
      runCmd: 'python -m services.server',
      tags: ['ai', 'web-app', 'fun'],
    },
    {
      id: 'scratchyfish',
      name: 'Scratchy Fish',
      tagline: 'Progressive jazz rock band website — scratchyfish.com',
      status: 'stable',
      techStack: ['Jekyll 4.3', 'HTML/CSS/JS', 'GitHub Pages'],
      path: '~/projects/personal/scratchyfish.com/',
      branch: 'main',
      uncommitted: true,
      uncommittedDetail: 'Modified .gitignore',
      openBranches: [],
      latestWork: 'Downloaded external images to local assets. Added Phil Bernosky bio & dog/person photo toggle. Layout refinements for full-width galleries.',
      runCmd: 'bundle exec jekyll serve',
      tags: ['website', 'band', 'static-site'],
    },
    {
      id: 'social-media-bot',
      name: 'Social Media Bot',
      tagline: 'AI content pipeline: git commits to social media posts',
      status: 'active',
      techStack: ['Python 3.12', 'Click', 'Claude Agent SDK', 'SQLite', 'tweepy', 'atproto'],
      path: '~/projects/personal/social-media-bot/',
      branch: 'main',
      uncommitted: true,
      uncommittedDetail: '11 modified/untracked files',
      openBranches: [],
      latestWork: 'Per-run data storage with live HTML dashboards. Deep commit-by-commit analysis pipeline. Interview system. Moved data to iCloud. Engagement feedback loops.',
      runCmd: 'smbot run',
      tags: ['ai', 'automation', 'social-media'],
    },
    {
      id: 'social-media-bot-tests',
      name: 'Social Media Bot Tests',
      tagline: 'Integration test harness for social-media-bot',
      status: 'stable',
      techStack: ['TypeScript', 'Vitest 3.2', 'better-sqlite3'],
      path: '~/projects/personal/social-media-bot-tests/',
      branch: 'main',
      uncommitted: false,
      uncommittedDetail: '',
      openBranches: [],
      latestWork: 'Test fixtures and roadmap management. 28 tests across 7 suites covering full pipeline, approval flow, auto-poster, health backoff.',
      runCmd: 'npm test',
      tags: ['testing', 'automation'],
    },
    {
      id: 'my-projects',
      name: 'My Projects',
      tagline: 'Cross-project docs & unified data architecture specs',
      status: 'new',
      techStack: ['Markdown', 'HTML/JS', 'SQLite (planned)'],
      path: '~/projects/personal/my-projects/',
      branch: 'main',
      uncommitted: true,
      uncommittedDetail: 'New project — untracked files (.gitignore, docs/, projects/)',
      openBranches: [],
      latestWork: 'Unified data abstraction spec for consolidating 3 agentic systems. Project summary files for all 8 projects. This dashboard.',
      runCmd: 'open index.html',
      tags: ['meta', 'documentation', 'architecture'],
    },
    // ── Agentic Cookbook ──
    {
      id: 'code-review-pipeline-test',
      name: 'Code Review Pipeline Test',
      tagline: 'KMP multiplatform app for testing Claude-powered PR review pipeline',
      status: 'active',
      techStack: ['Kotlin Multiplatform'],
      path: '~/projects/agentic-cookbook/code-review-pipeline-test/',
      branch: 'feature/cost-optimization', uncommitted: true, uncommittedDetail: '1 modified/untracked files',
      openBranches: ['chore/wrapper-refs-main', 'config/on-demand-reviews', 'config/update-dotfiles-reference', 'feature/add-anthropic-review', 'feature/agent-wrappers'],
      latestWork: 'Update dotfiles path references. Make Thorin code review on-demand only. Adopt combined review, make Anthropic on-demand.',
      runCmd: '', tags: ['agentic-cookbook', 'testing'],
    },
    {
      id: 'code-review-pipeline',
      name: 'Code Review Pipeline',
      tagline: 'Local daemon for automated GitHub PR reviews using Claude Code CLI',
      status: 'active',
      techStack: ['Python', 'Claude Code CLI', 'GitHub API'],
      path: '~/projects/agentic-cookbook/code-review-pipline/',
      branch: 'main', uncommitted: true, uncommittedDetail: '6 modified/untracked files', openBranches: [],
      latestWork: '', runCmd: '', tags: ['agentic-cookbook', 'automation', 'code-review'],
    },
    {
      id: 'cookbook',
      name: 'Cookbook',
      tagline: 'Structured cookbook of principles, guidelines, recipes, and workflows for AI-assisted development',
      status: 'active',
      techStack: ['Markdown', 'YAML', 'Claude Code'],
      path: '~/projects/agentic-cookbook/cookbook/',
      branch: 'main', uncommitted: true, uncommittedDetail: '1 modified/untracked files',
      openBranches: ['feature/cookbook-project-format', 'feature/ingredient-recipe-concoction', 'feature/move-site-design-rule', 'feature/platform-guidelines-reorg', 'feature/prefer-explicit-apple-apis'],
      latestWork: 'Reclassify recipes into ingredients. Add ingredient/recipe/concoction artifact hierarchy. Add skill test harness with Vitest + Claude CLI.',
      runCmd: '', tags: ['agentic-cookbook', 'documentation'],
    },
    {
      id: 'cookbook-tests',
      name: 'Cookbook Tests',
      tagline: 'Test output repository for agentic interview team workflows',
      status: 'active',
      techStack: ['Node.js', 'TypeScript'],
      path: '~/projects/agentic-cookbook/cookbook-tests/',
      branch: 'main', uncommitted: true, uncommittedDetail: '9 modified/untracked files', openBranches: [],
      latestWork: 'Add cc-plugin-eval research findings.',
      runCmd: '', tags: ['agentic-cookbook', 'testing'],
    },
    {
      id: 'cookbook-web',
      name: 'Cookbook Web',
      tagline: 'Documentation website for the agentic cookbook',
      status: 'active',
      techStack: ['Node.js', 'TypeScript', 'Claude Code'],
      path: '~/projects/agentic-cookbook/cookbook-web/',
      branch: 'main', uncommitted: true, uncommittedDetail: '200 modified/untracked files',
      openBranches: ['feature/add-site-design-rule'],
      latestWork: 'Add Open Graph and Twitter meta tags with branded OG image. Add Agentic Cookbook Family box with links. Style hero blurb in italic serif.',
      runCmd: '', tags: ['agentic-cookbook', 'website'],
    },
    {
      id: 'dev-team',
      name: 'Dev Team',
      tagline: 'Multi-agent dev team for project discovery, generation, building, and review',
      status: 'active',
      techStack: ['Python', 'Claude Code Plugins', 'HTML'],
      path: '~/projects/agentic-cookbook/dev-team/',
      branch: 'main', uncommitted: true, uncommittedDetail: '4 modified/untracked files', openBranches: [],
      latestWork: 'Update command references in planning docs. Replace command names: create-project-from-code → create-recipe-from-code.',
      runCmd: '', tags: ['agentic-cookbook', 'ai', 'agents'],
    },
    {
      id: 'dev-team-tests',
      name: 'Dev Team Tests',
      tagline: 'Test fixtures and output for dev-team agent workflows',
      status: 'active',
      techStack: [],
      path: '~/projects/agentic-cookbook/dev-team-tests/',
      branch: 'main', uncommitted: true, uncommittedDetail: '3 modified/untracked files', openBranches: [],
      latestWork: 'Initial test output repo setup.',
      runCmd: '', tags: ['agentic-cookbook', 'testing'],
    },
    {
      id: 'myagenticworkspace',
      name: 'My Agentic Workspace',
      tagline: 'Agentic workspace template repository',
      status: 'active',
      techStack: [],
      path: '~/projects/agentic-cookbook/myagenticworkspace/',
      branch: 'main', uncommitted: true, uncommittedDetail: '1 modified/untracked files', openBranches: [],
      latestWork: '', runCmd: '', tags: ['agentic-cookbook', 'template'],
    },
    {
      id: 'official-agent-registry',
      name: 'Official Agent Registry',
      tagline: 'Server and client for agent registry with database and API',
      status: 'active',
      techStack: ['Node.js', 'Claude Code'],
      path: '~/projects/agentic-cookbook/official-agent-registry/',
      branch: 'main', uncommitted: true, uncommittedDetail: '1 modified/untracked files', openBranches: [],
      latestWork: 'Add generalized AI persona research and template. Add favicon and apple-touch-icon. Add OG meta tags and preview image.',
      runCmd: '', tags: ['agentic-cookbook', 'infrastructure'],
    },
    {
      id: 'roadmaps',
      name: 'Roadmaps',
      tagline: 'Structured planning system for feature development with agent support',
      status: 'active',
      techStack: ['Claude Code Plugins', 'Markdown'],
      path: '~/projects/agentic-cookbook/roadmaps/',
      branch: 'main', uncommitted: true, uncommittedDetail: '4 modified/untracked files', openBranches: [],
      latestWork: 'Install agentic cookbook rule and manifest. Standardize progress output format.',
      runCmd: '', tags: ['agentic-cookbook', 'planning'],
    },
    {
      id: 'roadmaps-tests',
      name: 'Roadmaps Tests',
      tagline: 'Test output repository for roadmap system workflows',
      status: 'active',
      techStack: ['Claude Code'],
      path: '~/projects/agentic-cookbook/roadmaps-tests/',
      branch: 'main', uncommitted: true, uncommittedDetail: '1 modified/untracked files',
      openBranches: ['feature/AllAuto3Step-*'],
      latestWork: 'Add SingleStep roadmap fixture. Add AllAuto3Step roadmap fixture. Add WithDependencies roadmap fixture.',
      runCmd: '', tags: ['agentic-cookbook', 'testing'],
    },
    {
      id: 'agentic-tools',
      name: 'Agentic Tools',
      tagline: 'User-facing tools for interacting with the agentic cookbook system',
      status: 'active',
      techStack: ['Claude Code', 'Shell'],
      path: '~/projects/agentic-cookbook/tools/',
      branch: 'main', uncommitted: true, uncommittedDetail: '6 modified/untracked files', openBranches: [],
      latestWork: 'Add cookbook-statusline.sh script from dev-team repo. Initial commit: tools repo with rules, skills, and project setup.',
      runCmd: '', tags: ['agentic-cookbook', 'tools'],
    },
    // ── Apps ──
    {
      id: 'catnip',
      name: 'Catnip',
      tagline: 'iOS app with Claude backend integration and user profiles',
      status: 'active',
      techStack: ['Swift', 'Claude Code'],
      path: '~/projects/apps/catnip/',
      branch: 'main', uncommitted: true, uncommittedDetail: '1 modified/untracked files',
      openBranches: ['feature/catnipwebservice-step-4', 'feature/catnipwebservice-step-5', 'feature/deployment-step-12', 'feature/frontend-dashboard-step-10'],
      latestWork: 'Rename cat-herding → agentic-roadmaps. Refactor: rename runs to roadmaps across frontend, backend, and CLI. Migrate roadmaps to flat file format.',
      runCmd: '', tags: ['apps', 'ios', 'ai'],
    },
    {
      id: 'catnip-terminal',
      name: 'Catnip Terminal',
      tagline: 'Terminal-based interface companion to the Catnip iOS app',
      status: 'active',
      techStack: ['Swift', 'macOS', 'Xcode'],
      path: '~/projects/apps/catnip-terminal/',
      branch: 'feature/ai-session-summarization', uncommitted: true, uncommittedDetail: '2 modified/untracked files',
      openBranches: ['main', 'worktree-appkit-conversion'],
      latestWork: 'AI-powered session summarization with multi-provider support. Remove sidebar toggle from settings. Switch settings to sidebar layout per litterbox spec.',
      runCmd: '', tags: ['apps', 'terminal', 'macos'],
    },
    {
      id: 'hairball',
      name: 'Hairball',
      tagline: 'Native macOS menu bar app for window-level task context management',
      status: 'active',
      techStack: ['Swift', 'macOS', 'AppKit', 'Xcode'],
      path: '~/projects/apps/Hairball/',
      branch: 'main', uncommitted: true, uncommittedDetail: '14 modified/untracked files',
      openBranches: ['feature/HairballV1'],
      latestWork: 'Add Help window, Discovery window, oslog logging, rename contexts to Hairballs. Migrate roadmaps to flat file format.',
      runCmd: '', tags: ['apps', 'macos'],
    },
    {
      id: 'scratching-post',
      name: 'Scratching Post',
      tagline: 'macOS IDE enhancement with file browser improvements and window management',
      status: 'active',
      techStack: ['Swift', 'macOS', 'Xcode'],
      path: '~/projects/apps/scratching-post/',
      branch: 'main', uncommitted: true, uncommittedDetail: '2 modified/untracked files', openBranches: [],
      latestWork: 'Only update session summary on topic change, not every input. AI-powered session summarization with multi-provider support.',
      runCmd: '', tags: ['apps', 'macos', 'ide'],
    },
    {
      id: 'temporal',
      name: 'Temporal',
      tagline: 'Spec-driven cross-platform framework using Kotlin Multiplatform',
      status: 'active',
      techStack: ['Kotlin Multiplatform', 'Claude Code'],
      path: '~/projects/apps/temporal/',
      branch: 'main', uncommitted: false, uncommittedDetail: '',
      openBranches: ['feature/repo-reorg'],
      latestWork: 'Consolidate persona files and enrich naming research. Fix web smoke test CORS error and Apple CI build failure. Make seed discussion categories public.',
      runCmd: '', tags: ['apps', 'cross-platform'],
    },
    {
      id: 'temporal-platform',
      name: 'Temporal Platform',
      tagline: 'Specification repository for offline-first sync platform across Swift, Kotlin, and TypeScript',
      status: 'active',
      techStack: ['Markdown', 'Claude Code'],
      path: '~/projects/apps/temporal-platform/',
      branch: 'main', uncommitted: true, uncommittedDetail: '1 modified/untracked files', openBranches: [],
      latestWork: 'Rename cat-herding → agentic-roadmaps. Remove Swift .build artifacts and fix .gitignore.',
      runCmd: '', tags: ['apps', 'specs', 'cross-platform'],
    },
    {
      id: 'whippet',
      name: 'Whippet',
      tagline: 'macOS menu bar app monitoring Claude Code sessions in real time',
      status: 'active',
      techStack: ['Swift', 'macOS', 'AppKit', 'SQLite', 'Claude Code'],
      path: '~/projects/apps/Whippet/',
      branch: 'main', uncommitted: true, uncommittedDetail: '6 modified/untracked files', openBranches: [],
      latestWork: 'AI session summarization, frontmost window tracking, minimal UI. Snapshot app metadata on main thread, enumerate windows on background.',
      runCmd: '', tags: ['apps', 'macos', 'ai'],
    },
    // ── Paused ──
    {
      id: 'qualitytime',
      name: 'QualityTime',
      tagline: 'Time tracking and project management application',
      status: 'paused',
      techStack: ['Kotlin', 'Claude Code'],
      path: '~/projects/paused-projects/QualityTime/',
      branch: 'feature/agent-wrappers', uncommitted: true, uncommittedDetail: '1 modified/untracked files',
      openBranches: ['feature/anthropic-review', 'feature/thorin-code-review', 'fix/on-demand-reviews', 'main'],
      latestWork: 'Rename litterbox → agentic-cookbook. Update CLAUDE.md.',
      runCmd: '', tags: ['paused', 'productivity'],
    },
    {
      id: 'search-helper',
      name: 'Search Helper',
      tagline: 'macOS utility for enhanced search and file navigation',
      status: 'paused',
      techStack: ['Swift', 'macOS'],
      path: '~/projects/paused-projects/search-helper/',
      branch: 'main', uncommitted: true, uncommittedDetail: '1 modified/untracked files', openBranches: [],
      latestWork: 'Add architecture and design decision docs. Add SwiftUI SearchTermsApp target. Add Finder Sync Extension with host app.',
      runCmd: '', tags: ['paused', 'macos'],
    },
  ],

  todos: [
    { id: 'todo-1', projectId: 'my-agentic-interviews', title: 'Commit or revert 21 deleted Whippet cookbook files', priority: 'high', status: 'open', assignee: 'Mike' },
    { id: 'todo-2', projectId: 'mysetup', title: 'Commit 6 modified files on main', priority: 'medium', status: 'open', assignee: 'Mike' },
    { id: 'todo-3', projectId: 'mysetup', title: 'Complete remove-deprecated branch and merge', priority: 'medium', status: 'open', assignee: 'Mike' },
    { id: 'todo-4', projectId: 'cat-herding', title: 'Commit Site Manager template refactoring', priority: 'high', status: 'open', assignee: 'Mike' },
    { id: 'todo-5', projectId: 'cat-herding', title: 'Ship Site Manager v1.1 (messaging)', priority: 'low', status: 'open', assignee: 'Mike' },
    { id: 'todo-6', projectId: 'social-media-bot', title: 'Define brand voice guide (config/voice.md)', priority: 'medium', status: 'open', assignee: 'Mike' },
    { id: 'todo-7', projectId: 'social-media-bot', title: 'Connect live web search provider (replace stub)', priority: 'low', status: 'open', assignee: 'Mike' },
    { id: 'todo-8', projectId: 'my-projects', title: 'Initial git commit for my-projects repo', priority: 'high', status: 'open', assignee: 'Mike' },
    { id: 'todo-9', projectId: 'scratchyfish', title: 'Commit .gitignore change', priority: 'low', status: 'open', assignee: 'Mike' },
  ],

  issues: [
    { id: 'issue-1', projectId: 'my-agentic-interviews', title: 'Uncommitted deletions violate always-commit-and-push rule', severity: 'medium', status: 'open', detail: '21 Whippet cookbook files deleted locally but not committed. This breaks the project\'s own workflow rule.' },
    { id: 'issue-2', projectId: 'mysetup', title: 'git_commands.py contains hack that needs removal', severity: 'low', status: 'open', detail: 'TODO at line 8 — hack related to origin/foo branch removal.' },
  ],

  concerns: [
    { id: 'concern-1', projectId: 'cat-herding', title: 'Site Manager template complexity growing', status: 'monitoring', raiser: 'Mike', detail: '139 template files across 3 sites. Active refactoring may introduce breakage.' },
    { id: 'concern-2', projectId: 'social-media-bot', title: 'No live search provider connected', status: 'monitoring', raiser: 'Mike', detail: 'Online researcher bot uses a stub search provider. Limits research quality.' },
    { id: 'concern-3', projectId: 'my-projects', title: 'Unified data architecture not yet started', status: 'open', raiser: 'Mike', detail: 'Spec exists for consolidating 3 SQLite DBs into shared backend, but implementation hasn\'t begun.' },
  ],

  decisions: [
    { id: 'dec-1', projectId: 'social-media-bot', title: 'All drafts require human approval before posting', rationale: 'Brand safety and editorial control. No autonomous publishing.', decidedBy: 'Mike' },
    { id: 'dec-2', projectId: 'social-media-bot', title: 'Store data in iCloud Documents folder', rationale: 'Cross-device accessibility. Override with SMBOT_DATA_DIR env var.', decidedBy: 'Mike' },
    { id: 'dec-3', projectId: 'cat-herding', title: 'Local marketplace distribution model', rationale: 'Plugins stay self-contained and independently installable. No central registry needed.', decidedBy: 'Mike' },
    { id: 'dec-4', projectId: 'mysetup', title: 'Declarative setup.md manifest over imperative scripts', rationale: 'Single source of truth for machine state. Claude Code /setup skill interprets it.', decidedBy: 'Mike' },
    { id: 'dec-5', projectId: 'my-projects', title: 'localStorage adapter first, SQLite/API later', rationale: 'Get organized now. Swap adapter when web service is ready. Interface stays the same.', decidedBy: 'Mike' },
  ],

  dependencies: [
    { id: 'dep-1', projectId: 'social-media-bot-tests', title: 'Depends on social-media-bot Python venv', type: 'internal', status: 'healthy', detail: 'Tests execute Python bot via subprocess. Requires venv at social-media-bot/.venv/' },
    { id: 'dep-2', projectId: 'my-projects', title: 'Unified data spec depends on all 3 agentic projects', type: 'internal', status: 'pending', detail: 'Roadmaps, Dev-Team, and Social Media Bot must stabilize before unification begins.' },
    { id: 'dep-3', projectId: 'cat-herding', title: 'webinitor depends on external CLIs', type: 'external', status: 'healthy', detail: 'Requires wrangler, railway, gh, and GoDaddy API credentials.' },
    { id: 'dep-4', projectId: 'mysetup', title: 'Installs plugins from cat-herding', type: 'internal', status: 'healthy', detail: 'setup.md references cat-herding plugins for Claude Code installation.' },
  ],
};
